## Trying Some Basic Functions and Datatypes with NumPy

In [1]:
import numpy as np

### A Matrix

In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr = np.array([1.0,2.0,3.0])
arr

array([1., 2., 3.])

In [6]:
arr.dtype

dtype('float64')

<hr />

`np.zeros(shape, dtype=float)`
    
Return a new array of given shape and type, filled with zeros.
    
- shape : Shape of the new array, e.g., `(2, 3)` or `2`.
- dtype : The desired data-type for the array, e.g., `numpy.int8`. (Optional. Default is `numpy.float64`.)

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

<hr />

`np.ones(shape, dtype=float)`
    
Return a new array of given shape and type, filled with zeros.
    
- shape : Shape of the new array, e.g., `(2, 3)` or `2`.
- dtype : The desired data-type for the array, e.g., `numpy.int8`. (Optional. Default is `numpy.float64`.)

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

<hr />

`np.arange([start,]stop,[step])`

Returns an array of random numbers.
- Start: Where array start.
- Stop : Where array start (not included).
- Step : Difference between each element.

In [12]:
np.arange(1,10,2) # Array

array([1, 3, 5, 7, 9])

<hr />

`np.random.randn(row,column)`

Creates a matrix with random elements.
- row   : Number of rows 
- column: Number of columns

In [13]:
np.random.randn(10) # Creates array with random numbers

array([-0.33729651, -0.80809743, -0.30160637,  0.26481601,  0.64697433,
       -0.37782285, -1.39266096, -0.37346014, -0.36998739,  0.59617695])

In [14]:
np.random.randn(2,3) # Random Array with 2 rows and 3 columns

array([[-1.45208881, -0.20152571, -1.17397771],
       [-0.57206842,  0.88660015, -1.17509547]])

<hr />

`np.random.randint(low, high, size)`

Creates an array of random numbers if size provided or just a integer.
- low  : Lower limit
- high : Higher/ Upper limit (included)
- size : Number of elements in array
- dtype: Datatype of elements (int by default)

In [15]:
np.random.randint(0,5)

2

In [16]:
np.random.randint(0,100)

47

In [17]:
np.random.randint(0,100,10)

array([ 0, 26, 55, 76, 84,  2, 37, 55, 28, 93])