## Trying Some Basic Functions and Datatypes with NumPy

In [1]:
import numpy as np

### A Matrix

In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
### Array

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr = np.array([1.0,2.0,3.0])
arr

array([1., 2., 3.])

In [7]:
arr.dtype

dtype('float64')

<hr />

`np.zeros(shape, dtype=float)`
    
Return a new array of given shape and type, filled with zeros.
    
- shape : Shape of the new array, e.g., `(2, 3)` or `2`.
- dtype : The desired data-type for the array, e.g., `numpy.int8`. (Optional. Default is `numpy.float64`.)

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

<hr />

`np.ones(shape, dtype=float)`
    
Return a new array of given shape and type, filled with zeros.
    
- shape : Shape of the new array, e.g., `(2, 3)` or `2`.
- dtype : The desired data-type for the array, e.g., `numpy.int8`. (Optional. Default is `numpy.float64`.)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

<hr />

`np.arange([start,]stop,[step])`

Returns an array of random numbers.
- Start: Where array start.
- Stop : Where array start (not included).
- Step : Difference between each element.

In [13]:
np.arange(1,10,2) # Array

array([1, 3, 5, 7, 9])

<hr />

`np.random.randn(row,column)`

Creates a matrix with random elements.
- row   : Number of rows 
- column: Number of columns

In [14]:
np.random.randn(10) # Creates array with random numbers

array([ 0.20772865,  0.26598294,  0.37998383,  0.61944838, -0.10370382,
        1.00193025, -1.38422724, -1.48224147, -1.86214748,  0.46464071])

In [15]:
np.random.randn(2,3) # Random Array with 2 rows and 3 columns

array([[ 2.69374994, -0.29439635,  1.69377685],
       [ 1.71924145, -1.1301872 ,  0.22731719]])

<hr />

`np.random.randint(low, high, size)`

Creates an array of random numbers if size provided or just a integer.
- low  : Lower limit
- high : Higher/ Upper limit (included)
- size : Number of elements in array
- dtype: Datatype of elements (int by default)

In [16]:
np.random.randint(0,5)

0

In [17]:
np.random.randint(0,100)

72

In [18]:
np.random.randint(0,100,10)

array([51, 42, 34, 11, 91, 66, 78, 45, 11, 77])